/*
 For license information please see main.js.LICENSE.txt */
(function(t){var u=window.AmazonUIPageJS||window.P,x=u._namespace||u.attributeErrors,n=x?x("PRIVCONAssets@centralized-prompting",""):u;n.guardFatal?n.guardFatal(t)(n,window):n.execute(function(){t(n,window)})})(function(t,u,x){var n="function"===typeof Symbol&&"symbol"===typeof Symbol.iterator?function(m){return typeof m}:function(m){return m&&"function"===typeof Symbol&&m.constructor===Symbol&&m!==Symbol.prototype?"symbol":typeof m};t.when("3p-promise").register("@amzn/consent-orchestration-client-sdk",
function(m){var t;(function(){function p(){for(var a=arguments.length,b=Array(a),d=0;d<a;d++)b[d]=arguments[d];return b.join(".")}function H(a,b){(null==b||b>a.length)&&(b=a.length);for(var d=0,k=Array(b);d<b;d++)k[d]=a[d];return k}function Y(a){return a>Date.now()-z.promptTimeWindow*S}function q(a){var b=Date.now();return a>=z.promptsUntilCooldown?b+z.readCooldownDuration*S:void 0}function v(a){return v="function"==typeof Symbol&&"symbol"==n(Symbol.iterator)?function(a){return"undefined"===typeof a?
"undefined":n(a)}:function(a){return a&&"function"==typeof Symbol&&a.constructor===Symbol&&a!==Symbol.prototype?"symbol":"undefined"===typeof a?"undefined":n(a)},v(a)}function E(a,b){var d=Object.keys(a);if(Object.getOwnPropertySymbols){var k=Object.getOwnPropertySymbols(a);b&&(k=k.filter(function(b){return Object.getOwnPropertyDescriptor(a,b).enumerable}));d.push.apply(d,k)}return d}function r(a){for(var b=1;b<arguments.length;b++){var d=null!=arguments[b]?arguments[b]:{};b%2?E(Object(d),!0).forEach(function(b){var k,
e=d[b];a:if("object"==v(b)&&b){var c=b[Symbol.toPrimitive];if(void 0!==c){b=c.call(b,"string");if("object"!=v(b))break a;throw new TypeError("@@toPrimitive must return a primitive value.");}b=String(b)}(k="symbol"==v(b)?b:b+"")in a?Object.defineProperty(a,k,{value:e,enumerable:!0,configurable:!0,writable:!0}):a[k]=e}):Object.getOwnPropertyDescriptors?Object.defineProperties(a,Object.getOwnPropertyDescriptors(d)):E(Object(d)).forEach(function(b){Object.defineProperty(a,b,Object.getOwnPropertyDescriptor(d,
b))})}return a}function Z(a,b){var d,k=F(a,b),c=(d=k.prompts,[Date.now()].concat(function(a){if(Array.isArray(a))return H(a)}(d)||function(a){if("undefined"!=typeof Symbol&&null!=a[Symbol.iterator]||null!=a["@@iterator"])return Array.from(a)}(d)||function(a,b){if(a){if("string"==typeof a)return H(a,b);var d={}.toString.call(a).slice(8,-1);return"Object"===d&&a.constructor&&(d=a.constructor.name),"Map"===d||"Set"===d?Array.from(a):"Arguments"===d||/^(?:Ui|I)nt(?:8|16|32)(?:Clamped)?Array$/.test(d)?
H(a,b):void 0}}(d)||function(){throw new TypeError("Invalid attempt to spread non-iterable instance.\nIn order to be iterable, non-array objects must have a [Symbol.iterator]() method.");}()).filter(Y).sort(function(a,b){return b-a}).slice(0,z.promptsUntilCooldown));O(a,r(r({},k),{},{prompts:c,defer:q(c.length)}),b)}function F(a,b){var d=a.id(),c={principal:d,prompts:[]};try{var L=a.get(W);if(!L)return c;var e=JSON.parse(u.atob(L));return b.emitCount(p(b.appName,g.SERVICE,g.STORE,g.READ)),e.principal===
d?e:c}catch(M){return b.emitCount(p(b.appName,g.SERVICE,g.STORE,g.READ,g.ERROR)),c}}function O(a,b,d){try{var c=u.btoa(JSON.stringify(b));a.set(W,c);d.emitCount(p(d.appName,g.SERVICE,g.STORE,g.WRITE))}catch(L){d.emitCount(p(d.appName,g.SERVICE,g.STORE,g.WRITE,g.ERROR))}}function I(a){return I="function"==typeof Symbol&&"symbol"==n(Symbol.iterator)?function(a){return"undefined"===typeof a?"undefined":n(a)}:function(a){return a&&"function"==typeof Symbol&&a.constructor===Symbol&&a!==Symbol.prototype?
"symbol":"undefined"===typeof a?"undefined":n(a)},I(a)}function c(a){var b="function"==typeof Map?new Map:void 0;return c=function(a){function d(){return function(a,b,d){if(h())return Reflect.construct.apply(null,arguments);var c=[null];c.push.apply(c,b);c=new (a.bind.apply(a,c));return d&&G(c,d.prototype),c}(a,arguments,A(this).constructor)}if(null===a||!function(a){try{return-1!==Function.toString.call(a).indexOf("[native code]")}catch(e){return"function"==typeof a}}(a))return a;if("function"!=
typeof a)throw new TypeError("Super expression must either be null or a function");if(void 0!==b){if(b.has(a))return b.get(a);b.set(a,d)}return d.prototype=Object.create(a.prototype,{constructor:{value:d,enumerable:!1,writable:!0,configurable:!0}}),G(d,a)},c(a)}function h(){try{var a=!Boolean.prototype.valueOf.call(Reflect.construct(Boolean,[],function(){}))}catch(b){}return(h=function(){return!!a})()}function G(a,b){return G=Object.setPrototypeOf?Object.setPrototypeOf.bind():function(a,b){return a.__proto__=
b,a},G(a,b)}function A(a){return A=Object.setPrototypeOf?Object.getPrototypeOf.bind():function(a){return a.__proto__||Object.getPrototypeOf(a)},A(a)}function P(a){return P="function"==typeof Symbol&&"symbol"==n(Symbol.iterator)?function(a){return"undefined"===typeof a?"undefined":n(a)}:function(a){return a&&"function"==typeof Symbol&&a.constructor===Symbol&&a!==Symbol.prototype?"symbol":"undefined"===typeof a?"undefined":n(a)},P(a)}function x(){function a(a,f,b){return Object.defineProperty(a,f,{value:b,
enumerable:!0,configurable:!0,writable:!0}),a[f]}function b(a,f,b,d){f=Object.create((f&&f.prototype instanceof c?f:c).prototype);d=new G(d||[]);return A(f,"_invoke",{value:ca(a,b,d)}),f}function d(a,f,b){try{return{type:"normal",arg:a.call(f,b)}}catch(ba){return{type:"throw",arg:ba}}}function c(){}function g(){}function e(){}function M(b){["next","throw","return"].forEach(function(f){a(b,f,function(a){return this._invoke(f,a)})})}function h(a,b){function f(l,aa,c,e){l=d(a[l],a,aa);if("throw"!==l.type){var B=
l.arg;return(l=B.value)&&"object"==P(l)&&q.call(l,"__await")?b.resolve(l.__await).then(function(a){f("next",a,c,e)},function(a){f("throw",a,c,e)}):b.resolve(l).then(function(a){B.value=a;c(B)},function(a){return f("throw",a,c,e)})}e(l.arg)}var l;A(this,"_invoke",{value:function(a,d){function c(){return new b(function(b,l){f(a,d,b,l)})}return l=l?l.then(c,c):c()}})}function ca(a,b,c){var l=E;return function(f,e){if(l===H)throw Error("Generator is already running");if(l===z){if("throw"===f)throw e;
return{value:C,done:!0}}c.method=f;for(c.arg=e;;){if(f=c.delegate)if(f=Q(f,c)){if(f===D)continue;return f}if("next"===c.method)c.sent=c._sent=c.arg;else if("throw"===c.method){if(l===E)throw l=z,c.arg;c.dispatchException(c.arg)}else"return"===c.method&&c.abrupt("return",c.arg);l=H;f=d(a,b,c);if("normal"===f.type){if(l=c.done?z:I,f.arg===D)continue;return{value:f.arg,done:c.done}}"throw"===f.type&&(l=z,c.method="throw",c.arg=f.arg)}}}function Q(a,f){var b=f.method,l=a.iterator[b];if(l===C)return f.delegate=
null,"throw"===b&&a.iterator.return&&(f.method="return",f.arg=C,Q(a,f),"throw"===f.method)||"return"!==b&&(f.method="throw",f.arg=new TypeError("The iterator does not provide a '"+b+"' method")),D;b=d(l,a.iterator,f.arg);return"throw"===b.type?(f.method="throw",f.arg=b.arg,f.delegate=null,D):(b=b.arg)?b.done?(f[a.resultName]=b.value,f.next=a.nextLoc,"return"!==f.method&&(f.method="next",f.arg=C),f.delegate=null,D):b:(f.method="throw",f.arg=new TypeError("iterator result is not an object"),f.delegate=
null,D)}function n(a){var b={tryLoc:a[0]};1 in a&&(b.catchLoc=a[1]);2 in a&&(b.finallyLoc=a[2],b.afterLoc=a[3]);this.tryEntries.push(b)}function p(a){var b=a.completion||{};b.type="normal";delete b.arg;a.completion=b}function G(a){this.tryEntries=[{tryLoc:"root"}];a.forEach(n,this);this.reset(!0)}function t(a){if(a||""===a){var b=a[v];if(b)return b.call(a);if("function"==typeof a.next)return a;if(!isNaN(a.length)){var c=-1;b=function B(){for(;++c<a.length;)if(q.call(a,c))return B.value=a[c],B.done=
!1,B;return B.value=C,B.done=!0,B};return b.next=b}}throw new TypeError(P(a)+" is not iterable");}x=function(){return w};var C,w={},u=Object.prototype,q=u.hasOwnProperty,A=Object.defineProperty||function(a,b,c){a[b]=c.value},r="function"==typeof Symbol?Symbol:{},v=r.iterator||"@@iterator",F=r.asyncIterator||"@@asyncIterator",y=r.toStringTag||"@@toStringTag";try{a({},"")}catch(l){a=function(a,b,c){return a[b]=c}}w.wrap=b;var E="suspendedStart",I="suspendedYield",H="executing",z="completed",D={};r=
{};a(r,v,function(){return this});var J=Object.getPrototypeOf;(J=J&&J(J(t([]))))&&J!==u&&q.call(J,v)&&(r=J);var K=e.prototype=c.prototype=Object.create(r);return g.prototype=e,A(K,"constructor",{value:e,configurable:!0}),A(e,"constructor",{value:g,configurable:!0}),g.displayName=a(e,y,"GeneratorFunction"),w.isGeneratorFunction=function(a){a="function"==typeof a&&a.constructor;return!!a&&(a===g||"GeneratorFunction"===(a.displayName||a.name))},w.mark=function(b){return Object.setPrototypeOf?Object.setPrototypeOf(b,
e):(b.__proto__=e,a(b,y,"GeneratorFunction")),b.prototype=Object.create(K),b},w.awrap=function(a){return{__await:a}},M(h.prototype),a(h.prototype,F,function(){return this}),w.AsyncIterator=h,w.async=function(a,c,d,e,g){void 0===g&&(g=m);var f=new h(b(a,c,d,e),g);return w.isGeneratorFunction(c)?f:f.next().then(function(a){return a.done?a.value:f.next()})},M(K),a(K,y,"Generator"),a(K,v,function(){return this}),a(K,"toString",function(){return"[object Generator]"}),w.keys=function(a){var b=Object(a),
c=[],d;for(d in b)c.push(d);return c.reverse(),function N(){for(;c.length;){var a=c.pop();if(a in b)return N.value=a,N.done=!1,N}return N.done=!0,N}},w.values=t,G.prototype={constructor:G,reset:function(a){if(this.prev=0,this.next=0,this.sent=this._sent=C,this.done=!1,this.delegate=null,this.method="next",this.arg=C,this.tryEntries.forEach(p),!a)for(var b in this)"t"===b.charAt(0)&&q.call(this,b)&&!isNaN(+b.slice(1))&&(this[b]=C)},stop:function(){this.done=!0;var a=this.tryEntries[0].completion;if("throw"===
a.type)throw a.arg;return this.rval},dispatchException:function(a){function b(b,d){return l.type="throw",l.arg=a,c.next=b,d&&(c.method="next",c.arg=C),!!d}if(this.done)throw a;for(var c=this,d=this.tryEntries.length-1;0<=d;--d){var e=this.tryEntries[d],l=e.completion;if("root"===e.tryLoc)return b("end");if(e.tryLoc<=this.prev){var g=q.call(e,"catchLoc"),k=q.call(e,"finallyLoc");if(g&&k){if(this.prev<e.catchLoc)return b(e.catchLoc,!0);if(this.prev<e.finallyLoc)return b(e.finallyLoc)}else if(g){if(this.prev<
e.catchLoc)return b(e.catchLoc,!0)}else{if(!k)throw Error("try statement without catch or finally");if(this.prev<e.finallyLoc)return b(e.finallyLoc)}}}},abrupt:function(a,b){for(var c=this.tryEntries.length-1;0<=c;--c){var d=this.tryEntries[c];if(d.tryLoc<=this.prev&&q.call(d,"finallyLoc")&&this.prev<d.finallyLoc){var e=d;break}}e&&("break"===a||"continue"===a)&&e.tryLoc<=b&&b<=e.finallyLoc&&(e=null);c=e?e.completion:{};return c.type=a,c.arg=b,e?(this.method="next",this.next=e.finallyLoc,D):this.complete(c)},
complete:function(a,b){if("throw"===a.type)throw a.arg;return"break"===a.type||"continue"===a.type?this.next=a.arg:"return"===a.type?(this.rval=this.arg=a.arg,this.method="return",this.next="end"):"normal"===a.type&&b&&(this.next=b),D},finish:function(a){for(var b=this.tryEntries.length-1;0<=b;--b){var c=this.tryEntries[b];if(c.finallyLoc===a)return this.complete(c.completion,c.afterLoc),p(c),D}},catch:function(a){for(var b=this.tryEntries.length-1;0<=b;--b){var c=this.tryEntries[b];if(c.tryLoc===
a){a=c.completion;if("throw"===a.type){var d=a.arg;p(c)}return d}}throw Error("illegal catch attempt");},delegateYield:function(a,b,c){return this.delegate={iterator:t(a),resultName:b,nextLoc:c},"next"===this.method&&(this.arg=C),D}},w}function y(a,b,c,g,h,e,M){try{var d=a[e](M),k=d.value}catch(Q){return void c(Q)}d.done?b(k):m.resolve(k).then(g,h)}function T(){var a;return a=x().mark(function L(a,c){var d,g,k=arguments;return x().wrap(function(e){for(;;)switch(e.prev=e.next){case 0:d=2<k.length&&
void 0!==k[2]?k[2]:3,g=0;case 2:return e.prev=2,e.next=5,a(c);case 5:return e.abrupt("return",e.sent);case 8:if(e.prev=8,e.t0=e.catch(2),!(++g>=d)){e.next=13;break}throw e.t0;case 13:return e.next=15,new m(function(a){return setTimeout(a,100)});case 15:if(g<d){e.next=2;break}case 16:case "end":return e.stop()}},L,null,[[2,8]])}),T=function(){var c=this,g=arguments;return new m(function(d,e){function k(a){y(m,d,e,k,h,"next",a)}function h(a){y(m,d,e,k,h,"throw",a)}var m=a.apply(c,g);k(void 0)})},T.apply(this,
arguments)}function X(a,b,c,k){var d=b.appName;return function(a,b){return T.apply(this,arguments)}(a,k,4<arguments.length&&void 0!==arguments[4]?arguments[4]:3).then(function(a){return b.emitCount(p(d,g.SERVICE,c)),a}).catch(function(a){throw b.emitCount(p(d,g.SERVICE,c,g.ERROR)),new U("failed to ".concat(c.toLowerCase()," consent for ").concat(d),a);})}function da(a,b,c){var d=b||ea,h=c||fa;return{prompt:function(){return function(a,b,c){var d=b.appName;return function(a,b){var c;a=F(a,b);return Date.now()>
(null!==(c=a.defer)&&void 0!==c?c:0)}(c,b)?a().then(function(a){return b.emitCount(p(d,g.SERVICE,g.PROMPT)),Z(c,b),a}).catch(function(a){var e,k=a.status||(null===(e=a.http)||void 0===e?void 0:e.status)||0;if(429!==k&&204!==k)throw b.emitCount(p(d,g.SERVICE,g.PROMPT,g.ERROR)),new U("failed to prompt for consent for "+d,a);O(c,r(r({},F(c,b)),{},{defer:Date.now()+z.writeCooldownDuration*S}),b);!0}):function(a){return new m(function(b){a.emitCount(p(a.appName,g.SERVICE,g.PROMPT,g.SKIP));b(null)})}(b)}(a.prompt,
d,h)},accept:function(b){return X(a.accept,d,g.ACCEPT,b)},decline:function(b){return X(a.decline,d,g.DECLINE,b)},customize:function(){return function(a,b){var c=b.appName;return a().then(function(a){return b.emitCount(p(c,g.SERVICE,g.CUSTOMIZE)),a}).catch(function(a){throw b.emitCount(p(c,g.SERVICE,g.CUSTOMIZE,g.ERROR)),new U("failed to customize consent for "+c,a);})}(a.customize,d)}}}var R={d:function(a,b){for(var c in b)R.o(b,c)&&!R.o(a,c)&&Object.defineProperty(a,c,{enumerable:!0,get:b[c]})},
o:function(a,b){return Object.prototype.hasOwnProperty.call(a,b)},r:function(a){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(a,Symbol.toStringTag,{value:"Module"});Object.defineProperty(a,"__esModule",{value:!0})}},V={};R.r(V);R.d(V,{initialize:function(){return da}});var g=function(a){return a.SERVICE="cos",a.PROMPT="prompt",a.ACCEPT="accept",a.DECLINE="decline",a.CUSTOMIZE="customize",a.STORE="store",a.READ="read",a.WRITE="write",a.ERROR="error",a.SKIP="skip",a}({}),ea=
{appName:"unknown",emitCount:function(a,b){},emitTiming:function(a,b){}},z=JSON.parse('{"J":{"promptsUntilCooldown":5,"promptTimeWindow":10,"readCooldownDuration":15,"writeCooldownDuration":1440}}').J,S=6E4,W="sp-cc-pcl",fa={id:function(){return"unknown"},set:function(a,b){},get:function(a){return""}},U=function(a){function b(a,c){if(!(this instanceof b))throw new TypeError("Cannot call a class as a function");var d=b;var g=[a];d=A(d);d=h()?Reflect.construct(d,g||[],A(this).constructor):d.apply(this,
g);if(!d||"object"!=I(d)&&"function"!=typeof d){if(void 0!==d)throw new TypeError("Derived constructors may only return object or undefined");if(void 0===this)throw new ReferenceError("this hasn't been initialised - super() hasn't been called");d=this}return d.message=a,d.cause=c,d.cause=c,d.name="ConsentOrchestrationError",Object.setPrototypeOf(d,b.prototype),d}return function(a,b){if("function"!=typeof b&&null!==b)throw new TypeError("Super expression must either be null or a function");a.prototype=
Object.create(b&&b.prototype,{constructor:{value:a,writable:!0,configurable:!0}});Object.defineProperty(a,"prototype",{writable:!1});b&&G(a,b)}(b,a),c=b,Object.defineProperty(c,"prototype",{writable:!1}),c;var c}(c(Error));t=V})();return t});"use strict";t.when("A","3p-promise","a-util","@amzn/consent-orchestration-client-sdk","ready").execute("centralized-prompting",function(m,n,p,H){var x=function(c){return new n(function(h,n){m.post("/privacyprefs/retail/v3/banner",{params:{consent:c.payload.url},
paramsFormat:"json",accepts:"application/json",contentType:"application/json",timeout:5E3,headers:{"anti-csrftoken-a2z":c.csrfToken},success:function(c){h(c)},error:function(c){n(c)}})})},q=m.capabilities.localStorage?localStorage:{getItem:function(c){return null},setItem:function(c,h){},removeItem:function(c){}},v=u.ue&&"function"===typeof ue.count?function(c){return ue.count(c,1)}:function(c){},E=u.uet&&u.uex?{start:function(){return uet("bb","centralizedConsentBanner",{wb:1})},stop:function(){return uex("ld",
"centralizedConsentBanner",{wb:1})}}:{start:function(){},stop:function(){}};E.start();var r=H.initialize({prompt:function(){return new n(function(c,h){m.get("/privacyprefs/retail/v3/banner",{success:function(h){c(h)},error:function(c){h(c)}})})},accept:function(c){return x(c)},decline:function(c){return x(c)},customize:function(){return new n(function(c,h){c(null)})}},{appName:"sp",emitCount:v,emitTiming:function(c){}},{id:function(){return p.cookies.get("session-id")},get:function(c){return q.getItem(c)},
set:function(c,h){return q.setItem(c,h)}}),y=void 0,F=function(){var c=m.$("#cos-banner").outerHeight();"number"!==typeof c||0>=c||(m.capabilities.mobile?document.querySelector("#a-page").style.marginBottom=c+"px":document.body.style.paddingBottom=c+"px")},O=function(c){var h=m.$("#a-page \x3e *:not(script)").first();h.length?h.before(c):document.body.appendChild(c);t.when("a-expander").execute(function(c){c.initializeExpanders()})};r.prompt().then(function(c){if(c){var h=document.createElement("div");
h.id="sp-cc-wrapper";h.innerHTML=c;q.getItem("sp-cc-pending")&&(c=h.querySelector("#sp-cc-error"))&&(c.className=(" "+c.className+" ").replace(" aok-hidden "," "));q.removeItem("sp-cc-pending");O(h);E.stop();y=m.on("orientationchange resize",F);F()}}).catch(function(c){E.stop();throw c;});var I=function(){m.$("#sp-cc-wrapper").remove();q.setItem("sp-cc-pending","1");y&&m.off(y);F()};m.declarative("banner-accept-all","click",function(c){c.$event.preventDefault();var h=m.$("#cos-banner").find('[name\x3d"anti-csrftoken-a2z"]');
I();r.accept({payload:c.data,csrfToken:h.val()}).then(function(){q.removeItem("sp-cc-pending")})});m.declarative("banner-reject-all","click",function(c){c.$event.preventDefault();var h=m.$("#cos-banner").find('[name\x3d"anti-csrftoken-a2z"]');I();r.decline({payload:c.data,csrfToken:h.val()}).then(function(){q.removeItem("sp-cc-pending")})})})});